ARG UBUNTU_VERSION=20.04
ARG BUILD_ASSETS=ghcr.io/cheyilin/docker-wrk:build

FROM ${BUILD_ASSETS} AS builder
FROM ubuntu:${UBUNTU_VERSION}

LABEL maintainer="Cheyi Lin <cheyi.lin@gmail.com>"

SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]
RUN apt-get update; \
    apt-get install -y --no-install-recommends --no-install-suggests \
        netbase ca-certificates curl wget; \
    rm -rf /var/lib/apt/lists/*; \
    update-ca-certificates

COPY --from=builder /build/wrk /usr/local/bin/

RUN groupadd -r wrk && useradd -r -g wrk wrk
USER wrk

ENTRYPOINT ["wrk"]
