# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: docker
on:
  push:
    branches:
      - dev/**
    paths:
      - .github/**
      - src/**
      - deps/**
      - Dockerfile
      - Makefile
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_PLATFORMS: linux/amd64,linux/arm64
      BUILD_ASSETS: ghcr.io/cheyilin/docker-wrk:build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        # https://github.com/docker/metadata-action
        with:
          images: |
            ghcr.io/cheyilin/docker-wrk
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha,format=short,prefix=
          flavor: |
            latest=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        # https://github.com/docker/build-push-action
        with:
          context: .
          file: docker/Dockerfile.build
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: true
          cache-from: type=registry,ref=${{ env.BUILD_ASSETS }}
          cache-to: type=inline
          tags: |
            ${{ env.BUILD_ASSETS }}
      - name: Pack and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.pack
          platforms: ${{ env.BUILD_PLATFORMS }}
          build-args: |
            BUILD_ASSETS=${{ env.BUILD_ASSETS }}
          pull: true
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ steps.meta.outputs.tags }}
