# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: docker-build
on:
  workflow_dispatch:
  schedule:
    - cron: "11 2 * * *"
  push:
    branches:
      - dev/**
    paths:
      - docker/Dockerfile.build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.BUILD_PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build cache
        uses: docker/build-push-action@v2
        # https://github.com/docker/build-push-action
        with:
          context: .
          file: docker/Dockerfile.build
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/cheyilin/docker-wrk:build
